import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createBilling,nextMonth} from '../../supabase/functions/_shared/billing.mjs';
function fixture(){
 let state={payments:[]},time=Date.parse('2026-01-31T12:00:00Z'),serial=Promise.resolve();const remote=new Map(),calls=[];
 const config={YOOKASSA_SHOP_ID:'shop',YOOKASSA_SECRET_KEY:'test_example',LE_PRO_MONTHLY_PRICE:'990'};
 const read=async()=>structuredClone(state),update=fn=>{const p=serial.then(()=>{const clone=structuredClone(state);fn(clone);state=clone;});serial=p.catch(()=>{});return p;};
 const fetcher=async(url,o)=>{calls.push({url,...o});if(o.method==='POST'){const body=JSON.parse(o.body),key=o.headers['Idempotence-Key'];if(!remote.has(key))remote.set(key,{...body,id:'pay-'+remote.size,status:'pending',paid:false,test:true,recipient:{account_id:'shop'},confirmation:{confirmation_url:'https://yoomoney.ru/checkout/test'}});return Response.json(remote.get(key));}return Response.json([...remote.values()].find(p=>url.endsWith('/'+p.id)));};
 const billing=createBilling({read,update,env:k=>config[k],fetcher,now:()=>time});
 return {billing,read,calls,remote,config,setTime:t=>time=Date.parse(t),settle:()=>{const p=[...remote.values()].at(-1);Object.assign(p,{status:'succeeded',paid:true,payment_method:{id:'saved-card',type:'bank_card',saved:true,card:{last4:'4242',card_type:'Visa'}}});return p;}};
}
const checkout={email:'owner@example.com',method:'card',autoRenew:true};
test('payment amount is server-owned; confirmed payment grants all three features once',async()=>{const f=fixture();await f.billing.handle('checkout','POST',{...checkout,amount:1});assert.equal(JSON.parse(f.calls[0].body).amount.value,'299.00');f.settle();await Promise.all([f.billing.handle('refresh','POST'),f.billing.handle('refresh','POST')]);const s=await f.billing.handle('status','GET');assert.equal(s.end,'2026-02-28T12:00:00.000Z');assert.equal(s.autoRenew,true);for(const feature of s.features)await f.billing.requireFeature(feature);assert.equal(s.features.length,3);});
test('repeated checkout uses one provider idempotency key',async()=>{const f=fixture();await Promise.all([f.billing.handle('checkout','POST',checkout),f.billing.handle('checkout','POST',checkout)]);assert.equal(f.remote.size,1);assert.equal((await f.read()).payments.length,1);});
test('foreign product, amount, shop and test mode cannot activate access',async()=>{for(const mutate of [p=>p.metadata.product='genvito',p=>p.amount.value='1.00',p=>p.recipient.account_id='other',p=>p.test=false]){const f=fixture();await f.billing.handle('checkout','POST',checkout);mutate(f.settle());await assert.rejects(f.billing.handle('refresh','POST'),/не соответствует/);assert.equal((await f.billing.handle('status','GET')).active,false);}});
test('pending payment does not grant premium; stopped renewal retains paid period',async()=>{const f=fixture();await f.billing.handle('checkout','POST',checkout);await assert.rejects(f.billing.requireFeature('orders'),e=>e.status===402);f.settle();await f.billing.handle('refresh','POST');await f.billing.handle('auto-renew','POST',{enabled:false});assert.equal((await f.billing.handle('status','GET')).active,true);f.setTime('2026-03-01T00:00:00Z');await f.billing.renew();assert.equal(f.remote.size,1);await assert.rejects(f.billing.requireFeature('orders'));});
test('renewal waits for expiration and reconciles one pending attempt across runs',async()=>{const f=fixture();await f.billing.handle('checkout','POST',checkout);f.settle();await f.billing.handle('refresh','POST');await f.billing.renew();assert.equal(f.remote.size,1);f.setTime('2026-03-01T00:00:00Z');await Promise.all([f.billing.renew(),f.billing.renew()]);await f.billing.renew();assert.equal(f.remote.size,2);f.settle();await f.billing.renew();assert.equal((await f.billing.handle('status','GET')).end,'2026-04-01T00:00:00.000Z');});
test('detach stops recurring payments and removes saved card; cancellation grants no access',async()=>{const f=fixture();await f.billing.handle('checkout','POST',checkout);f.settle();await f.billing.handle('refresh','POST');await f.billing.handle('detach','POST');const s=await f.billing.handle('status','GET');assert.equal(s.card,null);assert.equal(s.autoRenew,false);assert.equal(s.active,true);const g=fixture();await g.billing.handle('checkout','POST',checkout);[...g.remote.values()][0].status='canceled';await g.billing.handle('refresh','POST');assert.equal((await g.billing.handle('status','GET')).active,false);});
test('card saving defaults on but provider saved=true is required',async()=>{const f=fixture();await f.billing.handle('checkout','POST',{...checkout,autoRenew:false});assert.equal(JSON.parse(f.calls[0].body).save_payment_method,true);f.settle();await f.billing.handle('refresh','POST');assert.equal((await f.billing.handle('status','GET')).autoRenew,true);const g=fixture();await g.billing.handle('checkout','POST',checkout);g.settle().payment_method.saved=false;await g.billing.handle('refresh','POST');assert.equal((await g.billing.handle('status','GET')).autoRenew,false);});
test('calendar months clamp dates, including leap years',()=>{assert.equal(nextMonth('2024-01-31T12:00:00Z'),'2024-02-29T12:00:00.000Z');assert.equal(nextMonth('2026-12-31T12:00:00Z'),'2027-01-31T12:00:00.000Z');});
test('quarterly and annual plans use their own price and period',async()=>{for(const [plan,amount,end] of [['3 месяца',799,'2026-04-30T12:00:00.000Z'],['6 месяцев',1490,'2026-07-31T12:00:00.000Z'],['1 год',2790,'2027-01-31T12:00:00.000Z']]){const f=fixture();await f.billing.handle('checkout','POST',{...checkout,plan});assert.equal(JSON.parse(f.calls[0].body).amount.value,amount.toFixed(2));f.settle();await f.billing.handle('refresh','POST');assert.equal((await f.billing.handle('status','GET')).end,end);}});
test('trial is unavailable and checkout needs no email; card auto-renews by default',async()=>{const f=fixture();await assert.rejects(f.billing.handle('checkout','POST',{plan:'3 дня',method:'card'}),/Выберите тариф/);await f.billing.handle('checkout','POST',{plan:'1 месяц',method:'card'});assert.equal(JSON.parse(f.calls[0].body).save_payment_method,true);f.settle();await f.billing.handle('refresh','POST');assert.equal((await f.billing.handle('status','GET')).autoRenew,true);});
